### ISSUE TITLE
If hiding UI: Health, Stamina, Magicka and other buff icons, still stays on screen. Is that a bug?

### ISSUE THREAD

**Issue by supremelight** [DakJaniels/LuiExtended#213] opened 2021-10-09 16:32 UTC
I tried to hide the UI for making screenshots of the game but some LUI extended's suffs still stays on screen.
Is that a bug?

**Comment by qaz1qaz1qa** [comment] 2023-08-12 01:44
Its August 2023 and I am having this issue.  So it must still be a bug.  Is it going to be addressed?  If it by chance is not a bug what am I missing. I have checked everything I can think of.  Uninstalled and deleted settings. Reinstalled and in the raw it still shows the character stat bars, Buffs, Pet bar, companion bar, Target bar and buffs.

This is an absolute deal breaker for me.  Thanks for the effort.  Truly appreciated.

**Comment by saenic** [comment] 2023-08-12 06:29
The thing is, I cannot reproduce it. For me everything hides when I use the ingame key to hide the UI.

**Comment by qaz1qaz1qa** [comment] 2023-08-13 04:24
I recall now a few days ago that I was in clear screen and did have it clear.  Then something happened where I was caught between full screen and there was a prompt.  Not sure if I was being pulled into an RND or something else.
Some things where showing and others would not.  I don't recall what that prompt asked me. But I am about 76% sure it was regarding clear screen mode or rather Hiding my UI or showing something in that mode.  I cannot find for the life of me any setting regarding that however.
I was searching some of the LIBs but so far no joy.  

I do remember that LUI was working to hide itself before that.

**Comment by qaz1qaz1qa** [comment] 2023-08-17 03:19
Ok I just swapped to Bandit UI. I have uninstalled LUI several times and deleted all the variables. I realized I will have to go though the long agonizing time it took me to get things back the way they where if I ever fix the bug. LUI is very difficult to set up.  Takes too long and is painstaking.  
I will miss a few features of LUI but I have found decent alternatives.

**Comment by ArtOfShred** [comment] 2023-08-24 04:33
This is likely an issue related to another addon. The first time I encountered this issue was with Essential Housing Tools. The author hooked the hide/unhide UI function (when you press toggle UI on/off) and something about that broke LUI's frames toggling off. I think this might have only happened when inside of a player house too. I don't have ESO installed and it's been way too long at this point so I'm not sure why exactly LUI had this issue. From what little I remember it was something like the hook called the hide UI function two times instead of just once and something about this caused LUI frames to toggle off and then right back on.

I added a function to toggle the frame visibility manually "function LUIE.ToggleVisibility(hidden)" in early 2020 and I think my gameplan was to see if the author of EHT could add the function to their hook.

Not sure if this is even relevant anymore, as EHT's code is probably quite a bit different - and I don't even know if EHT is causing the issue in this case. Saw this thread in my email & figured I'd at least chime in with what knowledge I have though.

It might be possible to hook the default ZOS Toggle UI function and call this function in there to fix the issue if it is EHT or another addon causing the issue.

**Comment by ArtOfShred** [comment] 2023-10-21 19:06
Can't replicate this currently. I tried installing EHT and that didn't cause any issues. Going to close this issue for now. If anyone encounters this issue again feel free to open a new issue - but to troubleshoot I will need your active addon list so I can try to replicate it myself. Thanks!

**Closed as completed by ArtOfShred** 2023-10-21 19:06 UTC
Labels: bug
